const PRICE_DATA={ios:[{uc:60,bonus:0,price:1100},{uc:325,bonus:25,price:5500},{uc:660,bonus:60,price:11000},{uc:1800,bonus:180,price:27500},{uc:3850,bonus:385,price:55000},{uc:8100,bonus:810,price:110000},{uc:16200,bonus:1620,price:220000}],android:[{uc:60,bonus:0,price:1100},{uc:325,bonus:25,price:5500},{uc:660,bonus:60,price:11000},{uc:1800,bonus:180,price:27500},{uc:3850,bonus:385,price:55000},{uc:8100,bonus:810,price:110000},{uc:16200,bonus:1620,price:220000}],midas:[{uc:60,bonus:0,price:1000},{uc:300,bonus:30,price:5000},{uc:660,bonus:60,price:10000},{uc:1800,bonus:180,price:25000},{uc:3850,bonus:385,price:50000},{uc:8100,bonus:810,price:100000},{uc:16200,bonus:1620,price:200000}]};
let platform="ios";const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const won=n=>"₩"+Math.round(n).toLocaleString("ko-KR"),fmt=n=>Math.round(n).toLocaleString("ko-KR");
function list(){let b=$("#bonus").checked;return PRICE_DATA[platform].map((p,i)=>({...p,index:i,total:p.uc+(b?p.bonus:0)}))}
function solve(target){let ps=list(),max=target+Math.max(...ps.map(p=>p.total)),dp=Array(max+1).fill(Infinity),prev=Array(max+1);dp[0]=0;
for(let i=0;i<=max;i++){if(!Number.isFinite(dp[i]))continue;for(let p of ps){let n=i+p.total;if(n<=max&&dp[n]>dp[i]+p.price){dp[n]=dp[i]+p.price;prev[n]={from:i,index:p.index}}}}
let best=target;for(let i=target;i<=max;i++)if(dp[i]<dp[best])best=i;let count=Array(ps.length).fill(0),x=best;while(x&&prev[x]){count[prev[x].index]++;x=prev[x].from}return{best,cost:dp[best],count,ps}}
function render(){let ps=PRICE_DATA[platform];$("#rows").innerHTML=ps.map(p=>{let total=p.uc+($("#bonus").checked?p.bonus:0);return`<tr><td><b>${fmt(p.uc)} UC</b></td><td>${fmt(p.uc)}</td><td>+${fmt(p.bonus)}</td><td>${fmt(total)}</td><td class="price">${won(p.price)}</td><td>${won(p.price/total*100)}</td></tr>`}).join("");let n=platform==="ios"?"iOS":platform==="android"?"Android":"MidasBuy";$("#tableName").textContent=n;$("#platformBadge").textContent=n}
function calculate(){let t=Math.floor(Number($("#uc").value));$("#error").textContent="";if(!t||t<1){$("#error").textContent="UC를 1 이상 입력해주세요.";return}if(t>1000000){$("#error").textContent="최대 1,000,000 UC까지 계산할 수 있습니다.";return}let r=solve(t);$("#empty").classList.add("hidden");$("#out").classList.remove("hidden");$("#badge").textContent="CALCULATED";let n=platform==="ios"?"iOS":platform==="android"?"Android":"MidasBuy";$("#target").innerHTML=`${fmt(t)} UC <em>${n}</em>`;$("#price").textContent=won(r.cost);$("#desc").textContent=`목표량을 충족하는 가장 저렴한 조합입니다.`;$("#actual").textContent=fmt(r.best)+" UC";$("#left").textContent="+"+fmt(r.best-t)+" UC";$("#extra").textContent="+"+fmt(r.best-t)+" UC";$("#packs").innerHTML=r.ps.map((p,i)=>r.count[i]?`<div class="pack"><span><i class="dot">●</i> ${fmt(p.uc)} UC 패키지 × ${r.count[i]}</span><b>${won(p.price*r.count[i])}</b></div>`:"").join("")}
$$(".platform").forEach(b=>b.onclick=()=>{$$(".platform").forEach(x=>x.classList.remove("active"));b.classList.add("active");platform=b.dataset.p;render();if(!$("#out").classList.contains("hidden"))calculate()});
$$("[data-uc]").forEach(b=>b.onclick=()=>{$("#uc").value=b.dataset.uc;calculate()});$("#calc").onclick=calculate;$("#uc").onkeydown=e=>{if(e.key==="Enter")calculate()};$("#bonus").onchange=()=>{render();if(!$("#out").classList.contains("hidden"))calculate()};$("#reset").onclick=()=>{$("#uc").value="";$("#out").classList.add("hidden");$("#empty").classList.remove("hidden");$("#badge").textContent="READY";$("#error").textContent=""};$("#theme").onclick=()=>document.body.classList.toggle("light");render();